name: 
  Build Main

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: 
      ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: npm install, validate and test
        run: |
          npm install
          npm run-script validate
          npm test
